### ISSUE TITLE
How to generate .ecx for Non-human species?

### ISSUE THREAD

**Issue by zhang121a** [LankyCyril/edgecase#11]
Hello,
I want to extend and identify telomeres in a non-human species using Edgecase, and I noticed that I need to generate an index with the suffix `.ecx`. However, I only found a script to generate an index for humans. Is there a script available to generate an index for other species?

**Comment by LankyCyril** [comment]
Hi! There's no such script, because fundamentally, an ECX is created based on "what you know," so it needs to be informed by literature / experience / research goals etc. As such, it basically needs to be custom-built by hand and might even be different from use case to use case.

The script that we provide for the human genome is actually mostly there to combine the hg38 fasta with the Stong _et al._ subtelomere fasta. It does also output an ECX, but if you look at the code, it's nothing more than decompressing a gzipped blob of data that contains what's in the hg38ext.fa.ecx. And the hg38ext.fa.ecx file itself was created by hand based on the mappings we obtained via the process described in "Methods -> The extended reference genome" in the paper: https://genome.cshlp.org/content/31/7/1269.full.pdf.
(Which was appropriate when the paper came out, but the T2T hs1 genome was released a couple of years later, and currently makes for a much better starting point, anyway).

So there's no one-size-fits-all approach here, sadly.
